### House Index
GET http://localhost:3000/properties.json

### House Create
POST http://localhost:3000/properties
Content-Type: application/json

{
  "title": "Test for proprty",
  "address": "Somewhere in Michigan",
  "description": "Nice House on the lake!!",
  "price_rate": 150,
  "max_guests": 6,
  "bedrooms": 3,
  "bathrooms": 2
}

### House Show
GET http://localhost:3000/properties/3

### Property Update
PATCH http://localhost:3000/properties/2
Content-Type: application/json

{
  "title": "Test title update",
  "address": "Test address update",
  "description": "Test description update",
  "price_rate": 500,
  "max_guests": 100,
  "bedrooms": 67,
  "bathrooms": 55,
  "service_fee": 789,
  "hot_tub": true,
  "pool": true,
  "laundry": true,
  "fireplace": true
}

### Property Delete
DELETE http://localhost:3000/properties/2