### House Index
GET http://localhost:3000/properties.json

### House Show
GET http://localhost:3000/properties/3

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "user_name": "Jdoe",
  "first_name": "John",
  "last_name": "Doe",
  "email": "john@doe.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "john@doe.com",
  "password": "password"
}

### Bookings create
POST http://localhost:3000/bookings.json
Content-Type: application/json

{
  "property_id": 1
}